sudo: required
services:
  - docker

before_install:
  - docker build -t luttferreira/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run luttferreira/react-test npm test -- --coverage
  
after_success:
  - docker build -t luttferreira/multi-client ./client
  - docker build -t luttferreira/multi-nginx ./nginx
  - docker build -t luttferreira/multi-server ./server
  - docker build -t luttferreira/multi-worker ./worker
  # Login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push luttferreira/multi-client
  - docker push luttferreira/multi-nginx
  - docker push luttferreira/multi-server
  - docker push luttferreira/multi-worker